export const CATEGORIES = {
	threed: { name: '3D', tag: '#3d' },
	game: { name: 'Game', tag: '#game' },
	tutorial: { name: 'Tutorial', tag: '#tutorial' },
	animation: { name: 'Animation', tag: '#animation' },
	art: { name: 'Art', tag: '#art' },
	online: { name: 'Online', tag: '#online' },
	music: { name: 'Music', tag: '#music' },
	platformer: { name: 'Platformer', tag: '#platformer' },
	contest: { name: 'Contest', tag: '#contest' },
	collaboration: { name: 'Collaboration', tag: '#collab' },
	story: { name: 'Story', tag: '#story' },
	utility: { name: 'Utility', tag: '#utility' },
	onesprite: { name: '1-Sprite', tag: '#1sprite' },
	extension: { name: 'Custom Extension', tag: '#extension' },
	os: { name: 'Operating System', tag: '#os' },
	meme: { name: 'Meme', tag: '#meme' },
}
