export const CATEGORIES = {
	'3D': '#3d',
	Game: '#game',
	Tutorial: '#tutorial',
	Animation: '#animation',
	Art: '#art',
	Online: '#online',
	Music: '#music',
	Platformer: '#platformer',
	Contest: '#contest',
	Collaboration: '#collab',
	Story: '#story',
	Utility: '#utility',
	'1-Sprite': '#1sprite',
	'Custom Extension': '#extension',
	'Operating System': '#os',
	Meme: '#meme',
}
