services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: aw3
      POSTGRES_PASSWORD: aw3 # we don't want to use this on deployment
      POSTGRES_DB: aw3
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  valkey:
    image: valkey/valkey:9.1
    ports:
      - '6379:6379'
    volumes:
      - valkey-data:/data
    command: valkey-server --save 60 1

volumes:
  db-data:
  valkey-data:
